swagger: "2.0"
info:
  title: RESTful API
  description: "[]"
  version: 1.0.0
paths:
  /JustATest:
    get:
      summary: Simplesmente um Teste
      tags:
        - Teste
      description: Só dar o clone pra começar o projeto.
      operationId: getTeste
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        200:
          description: OK
      x-swagger-router-controller: Method